export enum ErrorCode {
  VALIDATION_ERROR = "VALIDATION_ERROR",
  MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD",

  VM_NOT_FOUND = "VM_NOT_FOUND",
  VM_CREATION_FAILED = "VM_CREATION_FAILED",
  VM_DELETION_FAILED = "VM_DELETION_FAILED",
  VM_STATE_FETCH_FAILED = "VM_STATE_FETCH_FAILED",

  PULUMI_STACK_ERROR = "PULUMI_STACK_ERROR",

  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}

export const ErrorCodeToStatusMap: Record<ErrorCode, number>= {
  [ErrorCode.VALIDATION_ERROR]: 400,
  [ErrorCode.MISSING_REQUIRED_FIELD]: 400,
  [ErrorCode.VM_NOT_FOUND]: 404,
  [ErrorCode.VM_CREATION_FAILED]: 500,
  [ErrorCode.VM_DELETION_FAILED]: 500,
  [ErrorCode.VM_STATE_FETCH_FAILED]: 500,
  [ErrorCode.PULUMI_STACK_ERROR]: 500,
  [ErrorCode.INTERNAL_SERVER_ERROR]: 500,
};
